CC = gcc
CFLAGS = -Wall -Wextra -pthread -lcurl -lxml2
SRC = main.c
OBJ = $(SRC:.c=.o)
TARGET = crawler

all: $(TARGET)

$(TARGET): $(OBJ)
    $(CC) $(CFLAGS) -o $@ $^

%.o: %.c
    $(CC) $(CFLAGS) -c -o $@ $<

clean:
    rm -f $(OBJ) $(TARGET)
