CC=gcc
CFLAGS=-Wall -Wextra -Werror -pedantic
LIBS=-lcurl -lpthread -lxml2
TARGET=crawler
SRC=crawler.c
OBJ=crawler.o

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)

$(OBJ): $(SRC)
	$(CC) $(CFLAGS) -c -o $@ $^

clean:
	rm -f $(TARGET) $(OBJ)
